from app.schemas.job_description import (
    JobDescriptionCreate,
    JobDescriptionUpdate,
    JobDescriptionResponse,
)
from app.schemas.interview import (
    QuestionCreate,
    QuestionUpdate,
    QuestionResponse,
    InterviewCreate,
    InterviewUpdate,
    InterviewResponse,
    InterviewWithQuestions,
    GenerateQuestionsRequest,
    GenerateQuestionsResponse,
    EnhanceQuestionRequest,
    AITextResponse,
    GenerateRubricRequest,
    EnhanceRubricRequest,
)
from app.schemas.analysis import (
    QuestionInput,
    AnalysisRequest,
    QAPair,
    PreprocessingResult,
    QuestionScore,
    RelevanceResult,
    DetectedSkill,
    SoftSkillsResult,
    VideoResult,
    AudioResult,
    CandidateReport,
)
from app.schemas.softskills import (
    SoftSkillBankCreate,
    SoftSkillBankUpdate,
    SoftSkillBankResponse,
    SoftSkillKeysResponse,
)

__all__ = [
    "JobDescriptionCreate",
    "JobDescriptionUpdate",
    "JobDescriptionResponse",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionResponse",
    "InterviewCreate",
    "InterviewUpdate",
    "InterviewResponse",
    "InterviewWithQuestions",
    "GenerateQuestionsRequest",
    "GenerateQuestionsResponse",
    "EnhanceQuestionRequest",
    "AITextResponse",
    "GenerateRubricRequest",
    "EnhanceRubricRequest",

    "QuestionInput",
    "AnalysisRequest",
    "QAPair",
    "PreprocessingResult",
    "QuestionScore",
    "RelevanceResult",
    "DetectedSkill",
    "SoftSkillsResult",
    "VideoResult",
    "AudioResult",
    "CandidateReport",

    "SoftSkillBankCreate",
    "SoftSkillBankUpdate",
    "SoftSkillBankResponse",
    "SoftSkillKeysResponse",
]